#!/bin/bash

INSTANCE_HOME="/zope/instance"

if [ ! -d "$INSTANCE_HOME/etc" ]; then
  mkdir -p $INSTANCE_HOME
  sudo -u zope -g zope mkzopeinstance -u zope:2epoz -d $INSTANCE_HOME
  sudo -u zope -g zope cp /zope.conf $INSTANCE_HOME/etc/
fi

exec $INSTANCE_HOME/bin/zopectl fg
